name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn 
        uses: actions/setup-node@v2
        id: setup
        with:
          node-version: 15

      - name: yarn install
        if: steps.setup.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile --network-timeout 300000

      - name: yarn test
        run: |
          yarn lint
